# Generated by Django 3.0.6 on 2020-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuseraccount',
            name='username',
            field=models.CharField(default='exit', max_length=40, verbose_name='username'),
            preserve_default=False,
        ),
    ]
